name: Request repo
description: Request repo
title: "[REPO] <title>"
labels: [Repo Request]
assignees:
  - robandpdx_volcano

body:
- type: input
  id: repo-name
  attributes:
    label: Name
    description: Name of repo you are requesting
    placeholder: |
      Please follow these naming conventions...
  validations:
    required: true
- type: input
  id: repo-description
  attributes:
    label: Repo Description
    description: "Please provide a short description of your repo"
    placeholder: "Cool repo"
  validations:
    required: true
- type: dropdown
  id: team
  attributes:
    label: Teams Access
    multiple: true
    options:
      - Security (default)
      - UI
      - Mobile
      - API
      - Ops
      - Business
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
    options:
      - label: I agree to follow this Code of Conduct
        required: true