name: Create repo

on:
  issues:
    types: [opened]

jobs:
  parse-issue:
    runs-on: self-hosted
    outputs:
      payload: ${{ steps.issue_body_parser_request.outputs.payload }}
    steps:
      - name: Parse issue
        id: parse
        uses: onmax/issue-form-parser@v1.4
        with:
          issue_number: ${{ github.event.issue.number }}

      # Examples on how to use the output
      - name: Show parsed payload data
        run: |
          # Using the character `'` to prevent all characters enclosed within
          # them from being treated as special characters (e.g. $ or `)
          echo '${{ steps.parse.outputs.payload }}'
          echo '${{ fromJson(steps.parse.outputs.payload)["Name"] }}'
