name: Create repo

on:
  issues:
    types: [opened]

jobs:
  create-repo:
    runs-on: self-hosted
    outputs:
      payload: ${{ steps.issue_body_parser_request.outputs.payload }}
    steps:
      - name: Parse issue
        id: parse
        uses: onmax/issue-form-parser@v1.4
        with:
          issue_number: ${{ github.event.issue.number }}

      # Examples on how to use the output
      - name: Show parsed payload data
        env:
          NAME: ${{ fromJson(steps.parse.outputs.payload).Name }}
          DESCRIPTION: ${{ fromJson(steps.parse.outputs.payload).Description }}
          TEAMS: ${{ join(fromJson(steps.parse.outputs.payload).Teams, ',') }}
        run: |
          # Using the character `'` to prevent all characters enclosed within
          # them from being treated as special characters (e.g. $ or `)
          echo '${{ steps.parse.outputs.payload }}'
          echo "NAME: $NAME"
          echo "DESCRIPTION: $DESCRIPTION"
          echo "TEAMS: $TEAMS"
      - name: Checkout admin repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.ORG }}/admin
          token: ${{ secrets.ADMIN_TOKEN }}
          path: admin
      - name: Create new repo setting from template
        uses: bluwy/substitute-string-action@v1
        with:
          _input-file: admin/${{ env.TEMPLATE }}
          _output-file: admin/.github/repos/${{ fromJson(steps.parse.outputs.payload).Name }}.yml
          _format-key: '%%key%%'
          NAME: ${{ fromJson(steps.parse.outputs.payload).Name }}
          DESCRIPTION: ${{ fromJson(steps.parse.outputs.payload).Description }}
          TEAMS: ${{ join(fromJson(steps.parse.outputs.payload).Teams, ',') }}

      - name: Add teams to repos access config
        env:
          NAME: ${{ fromJson(steps.parse.outputs.payload).Name }}
          TEAMS: ${{ join(fromJson(steps.parse.outputs.payload).Teams, ',') }}
        run: |
          echo Adding $TEAMS to repo access config
          IFS=',' read -r -a array <<< "$TEAMS"

          for team in "${array[@]}"
          do
              echo "Adding $team to repo access config"
              cat <<EOF >> admin/.github/repos/$NAME.yml
            - name: $team
              permission: push
          EOF
          done

      - name: Show the new repo settings
        env:
          NAME: ${{ fromJson(steps.parse.outputs.payload).Name }}
        run: cat admin/.github/repos/$NAME.yml

      - name: Commit and push new repo settings file
        uses: EndBug/add-and-commit@v9
        with:
          add: .github/repos/${{ fromJson(steps.parse.outputs.payload).Name }}.yml
          cwd: ./admin
          default_author: github_actor
          message: Repo settings for ${{ fromJson(steps.parse.outputs.payload).Name }}
          push: true
      - name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: Auto-closing issue upon successful repo creation