name: Create repo

on:
  issues:
    types: [opened]

jobs:
  parse-issue:
    runs-on: self-hosted
    outputs:
      payload: ${{ steps.issue_body_parser_request.outputs.payload }}
    steps:
      - name: Parse issue
        id: parse
        uses: onmax/issue-form-parser@v1.4
        with:
          issue_number: ${{ github.event.issue.number }}

      # Examples on how to use the output
      - name: Show parsed payload data
        env:
          NAME: ${{ fromJson(steps.parse.outputs.payload).Name }}
          DESCRIPTION: ${{ fromJson(steps.parse.outputs.payload).Description }}
        run: |
          # Using the character `'` to prevent all characters enclosed within
          # them from being treated as special characters (e.g. $ or `)
          echo '${{ steps.parse.outputs.payload }}'
          echo "NAME: $NAME"
          echo "DESCRIPTION: $DESCRIPTION"
          echo "TEAMS: ${{ join(fromJson(steps.parse.outputs.payload).Teams, ',') }}"
      - name: Checkout admin repo
        uses: actions/checkout@v2
        with:
          repository: robandpdx-volcano/admin
          token: ${{ secrets.ADMIN_TOKEN }}
          path: admin
      - name: Create new repo setting from template
        env:
          NAME: ${{ fromJson(steps.parse.outputs.payload).Name }}
          DESCRIPTION: ${{ fromJson(steps.parse.outputs.payload).Description }}
        uses: bluwy/substitute-string-action@v1
        with:
          _input-file: admin/templates/repo-template.yml
          _output-file: admin/.github/repos/${{ fromJson(steps.parse.outputs.payload).Name }}.yml
          _format-key: '%%key%%'
          NAME: $NAME
          DESCRIPTION: $DESCRIPTION
          TEAMS: ${{ join(fromJson(steps.parse.outputs.payload).Teams, ',') }}

      - name: Show the new repo settings
        env:
          NAME: ${{ fromJson(steps.parse.outputs.payload).Name }}
        run: cat admin/.github/repos/$NAME.yml
