name: Create repo

on:
  issues:
    types: [opened]

jobs:
  parse-issue:
    runs-on: self-hosted
    outputs:
      payload: ${{ steps.issue_body_parser_request.outputs.payload }}
    steps:
      - name: Run Issue form parser
        id: parse
        uses: peter-murray/issue-forms-body-parser@v2.0.0
        with:
          issue_id: ${{ github.event.issue.number }}
          separator: '###'
          label_marker_start: '>>'
          label_marker_end: '<<'

      - name: Show parsed data JSON
        run: |
          echo "${{ steps.parse.outputs.payload }}"
